# Generated by Django 2.0.3 on 2018-03-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('radius', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('time', models.DateTimeField()),
                ('is_safe', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('phone', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('related_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_related_users', to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to='api.User'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_fencing_user', to='api.User'),
        ),
    ]
