# Generated by Django 2.0.3 on 2018-03-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lon',
            new_name='long',
        ),
    ]
